version: '3'
services:
  backend:
    build: ./backend/
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - postgresql
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
  postgresql:
    image: postgres:latest
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=erfan
      - POSTGRES_PASSWORD=erfan1234
      - POSTGRES_DB=django
    
  frontend:
    build: ./frontend/
    command: "npm run serve"
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

volumes:
  postgresdata:


